@Basket_HostAddress = https://localhost:7259/basket

GET {{Basket_HostAddress}}/leetrent/
Accept: application/json

###
POST {{Basket_HostAddress}}
Content-Type: application/json
{
    "UserName": "leetrent",
    "Items": [
        {
        "Quantity": 2,
        "Color": "Red",
        "Price": 500,
        "ProductId": 1,
        "ProductName": "Solar Powered Flashlight"
        },
        {
        "Quantity": 1,
        "Color": "Blue",
        "Price": 500,
        "ProductId": 2,
        "ProductName": "Hiking Poles"
        }
    ]
}

###

DELETE {{Basket_HostAddress}}/leetrent
Content-Type: application/json

###
